config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :attendees
  resources :events do
    post :attend, on: :member
    post :leave, on: :member
  end
  resources :blogs
  resources :users do
    get :approve, on: :member
  end
  root to: 'visitors#index'
  get '/welcome' => "pages#welcome"
  get '/community' => "pages#community"
    get '/videos' => "pages#videos"
  get '/contact' => "pages#contact"
    get '/fun' => "pages#fun"
  get '/general-education' => "pages#general-education"
    get '/troubleshooting' => "pages#troubleshooting"
  get '/Security' => "pages#Security"
  get '/debate-info' => "pages#debate-info"
  get '/Assembly' => "pages#Assembly"
  get '/court' => "pages#court"
  get '/special' => "pages#special"
  get '/jro-mun' => "pages#jro-mun"
  get '/advise' => "pages#advise"
    get '/internationalAffairs' => "pages#internationalAffairs"

 get '/community' => "pages#community"

  get '/omunresources' => "pages#omunresources"
  get '/contact' => "pages#contact"
    get '/hela' => "pages#hela"
  get '/thimun_qatar' => "pages#thimun_qatar"
  
  get '/thimun-o-mun-rules-and-procedures' => "pages#thimun-o-mun-rules-and-procedures"
  
  get '/speech-making-and-forms-address' => "pages#speech-making-and-forms-address"
  get '/opening-speeches-policy-statements-and-draft-resolutions' => "pages#opening-speeches-policy-statements-and-draft-resolutions"
  get '/commonly-used-terms' => "pages#commonly-used-terms"
  get '/debate-procedure' => "pages#debate-procedure"
  get '/specific-rules-and-procedures-online-debates' => "pages#specific-rules-and-procedures-online-debates"
  get '/draft-resolution' => "pages#draft-resolution"
  get '/words-and-phrases-drafting-resolutions' => "pages#words-and-phrases-drafting-resolutions"
  get '/stock-chairing-phrases' => "pages#stock-chairing-phrases"

  
  get '/writing-thimun-resolution' => "pages#writing-thimun-resolution"
  
  get '/purpose-resolution' => "pages#purpose-resolution"
  get '/heading' => "pages#heading"
  get '/first-line' => "pages#first-line"
  get '/preambulatory-clauses' => "pages#preambulatory-clauses"
  get '/operative-clauses' => "pages#operative-clauses"
  get '/sample-resolution' => "pages#sample-resolution"
  

  
  get '/thimun-o-mun-delegate-guide' => "pages#thimun-o-mun-delegate-guide"
  
    
  get '/thimun-o-mun-vision' => "pages#thimun-o-mun-vision"
  get '/introduction' => "pages#introduction"
  get '/technology' => "pages#technology"
  get '/debating-blackboard-collaborate' => "pages#debating-blackboard-collaborate"
  get '/debate-procedure-step-step' => "pages#debate-procedure-step-step"
  get '/rules-procedures-online-equivalents' => "pages#rules-procedures-online-equivalents"
  get '/debate-cycles-country-assignments' => "pages#debate-cycles-country-assignments"
  get '/moderating-chairing' => "pages#moderating-chairing"

  
  get '/power-search' => "pages#power-search" 
  get '/un-guide-model-united-nations' => "pages#un-guide-model-united-nations" 

  
  
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  
  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
        belongs_to :user, foreign_key: :user_id
        mount_uploader :picture, EvntpictureUploader
        
        validates :title, :body, presence: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    def authorize
      if !current_user
         redirect_to :login , :alert => "You must be logged in to access this page"
      end
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:user_id, :title, :picture, :show_info, :body)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<div class="row">
  <div class="col-lg-6" style="padding-left:30px;">
<%= simple_form_for(@blog) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body, :input_html => {:rows => 8} %>
    <%= f.input :show_info, label: "Show Author Info"%>
    <%= f.input :picture,   as: :file, label: "Thumbnail (optional)", wrapper_html: { id: 'pictureInput' } %>
    <div id="target" style="width:600px;height:200px;"></div>

  </div>
  
  
  <div class= "row">
    <div class="col-lg-2">
      <div class="form-actions">
        <%= f.button :submit, "Apply Changes" %>
      </div>
    </div>
    
    <div class="col-lg-1">
      <% if Blog.exists?(params[:id]) %>
      <%= link_to 'Cancel', blog_path, class: "btn btn-danger", :style => "color:white;" %>
      <% else %>
      <%= link_to 'Cancel', blogs_path, class: "btn btn-danger", :style => "color:white;" %>
      <% end %>
    </div>
  </div>
  </div>
</div>
<% end %>






<script>
  $(function() {
  $('#pictureInput').on('change', function(event) {
    var files = event.target.files;
    var image = files[0]
    // here's the file size
    console.log(image.size);
    var reader = new FileReader();
    reader.onload = function(file) {
      var img = new Image();
      console.log(file);
      img.src = file.target.result;
      img.height = 200;
      $('#target').html(img);
    }
    reader.readAsDataURL(image);
    console.log(files);
  });
});
</script>

app/views/blogs/edit.html.erb
<section style="margin-bottom:20px;" class="black">
       
<h2 style="padding-left:20px;">Editing Blog</h2>
</section>
<%= render 'form' %>

app/views/blogs/index.html.erb
  <%= render "layouts/navigation"%>
     <section class="green" style="background-color:#70d370">
       
<h1 style ="margin-left:25px;margin-top:50px; margin-bottom:10px;font-size:70px;">Blog</h1>
     </section>
<p id="notice"><%= notice %></p>


    <% @blogs.reverse_each do |blog| %>

        <div class="row" style="margin-left:20px;">
            <div class="col-sm-11">
                <div class="card"  style="margin-bottom:10px;">
                  <div class="card-content">
                      <div class="row">
                      <div class="col-lg-2"> <img src="<%= blog.picture %>" style="width:200px;height:200px;"/></div>

                      <div class="col-lg-9">
                        <h3 class="card-title"><%= blog.title %>  
                        <% if (current_user && ( current_user.id == blog.user_id || current_user.priv_lvl > 1 )) %>
                        <span> <%= link_to blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger', :style => "float:right;color:white;" do %>
                            <i class="glyphicon glyphicon-trash"></i>
                          <%end%>
                          
                          <%= link_to edit_blog_path(blog), class: 'btn btn-default', :style => "float:right;margin-right:10px;" do %>
                            <i class="glyphicon glyphicon-edit"></i>
                          <%end%>
                          <%end%>
                          </span></h3> 
                        <h5 class="card-subtitle mb-2 text-muted">by: <strong><%= User.find(blog.user_id).fname %></strong>
                        
                        <% yesterday = Time.zone.now- 1.day %>
                        <% if  blog.created_at >= Time.zone.now.beginning_of_day %>
                        , Today 
                        <% elsif blog.created_at >= yesterday.beginning_of_day && blog.created_at <= yesterday.end_of_day  %>
                        , Yesterday
                        <% else %>
                         on  <b> <%= blog.created_at.to_date %> 
                        <% end %>
                        
                        
                        </h5>
                        <p style="margin-bottom:20px;"class="card-text"><%= blog.body[0,300] %> <% if blog.body.length > 300 %> ... <%end%></p>
                        <%= link_to 'Read more...', blog %> 
                        <% if current_user %>
                        <% end %>
                        </div>
                    </div>
                  </div>
                </div>
        </div>
        
        </div>

    <% end %>


<br>
<% if current_user %>
     <div class="col-md-6"><%= link_to new_blog_path, class: 'btn btn-success', :style => "color:white;" do %>
                            <i class="glyphicon glyphicon-plus"></i> New Post
                          <%end%></div>
<% end %>

app/views/blogs/new.html.erb
<section style="margin-bottom:20px;" class="black">
       
<h2 style="padding-left:20px;">New Blog</h2>
</section>

<%= render 'form' %>

app/views/blogs/show.html.erb
<%= render "layouts/navigation" %>
<section  style="background-image: image-url("assets/BlogBanner.png");">

</secion>
<body style="padding-left:20px;">
  
<p id="notice"><%= notice %></p>

<p>
  
  <h2 style="font-size:80px;font-weight:800;"> <%= @blog.title %> </h2>
</p>

<p style="font-size:20px;color:#e2e2e2;margin-top:15px;">
  by
  <%= User.find(@blog.user_id).fname %> <%= User.find(@blog.user_id).lname %>
  
                          <% yesterday = Time.zone.now- 1.day %>
                        <% if  @blog.created_at >= Time.zone.now.beginning_of_day %>
                        , Today 
                        <% elsif @blog.created_at >= yesterday.beginning_of_day && @blog.created_at <= yesterday.end_of_day  %>
                        , Yesterday
                        <% else %>
                         on  <b> <%= @blog.created_at.to_date %> 
                        <% end %>
</p>


<div class="row">
  <div class="col-lg-7">
<p style="margin-top:30px;font-size:1.1em;line-height:1.1em;font-weight:400;margin-bottom:50px;">
  <%= @blog.body %>
<p>
</div>
</div>

<div class="row">
  <div class="col-lg-5">
    
<% if @blog.show_info %>

        <div class="card" >
          <div class="card-content">
            <h1 class="card-title" style="margin-top:-7px;"> About the Author </h1>
            <div class="row">
              <div class="col-lg-3">
                 <img src=<%= User.find(@blog.user_id).avatar %>  class="img-circle"  width="120" height="120" style="margin-left:20px;" > </a>
              </div>
              <div class="col-lg-9" style="margin-top:20px;" >
                  <p class="card-text" style="margin-bottom:3px;"> <i class="glyphicon glyphicon-user"></i> <%= User.find(@blog.user_id).fname %> <%= User.find(@blog.user_id).lname %></p>
                  <p class="card-text" style="margin-bottom:3px;"> <i class="glyphicon glyphicon-envelope"></i> <%= User.find(@blog.user_id).email %></p>
                  <p class="card-text" style="margin-bottom:3px;"> <i class="glyphicon glyphicon-globe"></i> <%= User.find(@blog.user_id).city %> , <%= User.find(@blog.user_id).counrty %></p>
                  <p class="card-text" style="margin-bottom:3px;"> <i class="glyphicon glyphicon-briefcase"></i> <%= User.find(@blog.user_id).occupation %></p>
              </div>

            </div>

          </div>
        </div>
        
<% end %>

</div>
</div>
<div class="row" style="margin-top:20px;">
  <% if current_user && @blog.user_id = current_user.id %>
  <div class="col-lg-1"> <%= link_to edit_blog_path(@blog), class: "btn btn-default", :style => "display:block;" do %><i class="glyphicon glyphicon-edit"></i> Edit <% end %></div>
  <%end%>
  <div class="col-lg-1"> <%= link_to  blogs_path, class: "btn btn-danger", :style => "color:white;display:block;" do %> <i class="glyphicon glyphicon-chevron-left"> </i> Back<% end %></div>


</div>
</body>