config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :attendees
  resources :events do
    post :attend, on: :member
    post :leave, on: :member
  end
  resources :blogs
  resources :users do
    get :approve, on: :member
  end
  root to: 'visitors#index'
  get '/welcome' => "pages#welcome"
  get '/community' => "pages#community"
    get '/videos' => "pages#videos"
  get '/contact' => "pages#contact"
    get '/fun' => "pages#fun"
  get '/general-education' => "pages#general-education"
    get '/troubleshooting' => "pages#troubleshooting"
  get '/Security' => "pages#Security"
  get '/debate-info' => "pages#debate-info"
  get '/Assembly' => "pages#Assembly"
  get '/court' => "pages#court"
  get '/special' => "pages#special"
  get '/jro-mun' => "pages#jro-mun"
  get '/advise' => "pages#advise"
    get '/internationalAffairs' => "pages#internationalAffairs"

 get '/community' => "pages#community"

  get '/omunresources' => "pages#omunresources"
  get '/contact' => "pages#contact"
    get '/hela' => "pages#hela"
  get '/thimun_qatar' => "pages#thimun_qatar"
  
  get '/thimun-o-mun-rules-and-procedures' => "pages#thimun-o-mun-rules-and-procedures"
  
  get '/speech-making-and-forms-address' => "pages#speech-making-and-forms-address"
  get '/opening-speeches-policy-statements-and-draft-resolutions' => "pages#opening-speeches-policy-statements-and-draft-resolutions"
  get '/commonly-used-terms' => "pages#commonly-used-terms"
  get '/debate-procedure' => "pages#debate-procedure"
  get '/specific-rules-and-procedures-online-debates' => "pages#specific-rules-and-procedures-online-debates"
  get '/draft-resolution' => "pages#draft-resolution"
  get '/words-and-phrases-drafting-resolutions' => "pages#words-and-phrases-drafting-resolutions"
  get '/stock-chairing-phrases' => "pages#stock-chairing-phrases"

  
  get '/writing-thimun-resolution' => "pages#writing-thimun-resolution"
  
  get '/purpose-resolution' => "pages#purpose-resolution"
  get '/heading' => "pages#heading"
  get '/first-line' => "pages#first-line"
  get '/preambulatory-clauses' => "pages#preambulatory-clauses"
  get '/operative-clauses' => "pages#operative-clauses"
  get '/sample-resolution' => "pages#sample-resolution"
  

  
  get '/thimun-o-mun-delegate-guide' => "pages#thimun-o-mun-delegate-guide"
  
    
  get '/thimun-o-mun-vision' => "pages#thimun-o-mun-vision"
  get '/introduction' => "pages#introduction"
  get '/technology' => "pages#technology"
  get '/debating-blackboard-collaborate' => "pages#debating-blackboard-collaborate"
  get '/debate-procedure-step-step' => "pages#debate-procedure-step-step"
  get '/rules-procedures-online-equivalents' => "pages#rules-procedures-online-equivalents"
  get '/debate-cycles-country-assignments' => "pages#debate-cycles-country-assignments"
  get '/moderating-chairing' => "pages#moderating-chairing"

  
  get '/power-search' => "pages#power-search" 
  get '/un-guide-model-united-nations' => "pages#un-guide-model-united-nations" 

  
  
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
    mount_uploader :avatar, AvatarUploader
    has_secure_password
    
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
     
    validates :fname, :lname, presence: true
    validates :password, :password_confirmation, presence: true
    validates :email, presence: true, length: { minimum: 6, maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :approve]
  before_action :authorize, only: [:index, :edit, :update, :destroy, :approve]
  skip_before_action :authenticate, only: [:new, :create]


  # GET /users
  # GET /users.json
  def index
    if current_user.priv_lvl < 2
      redirect_to :root , :alert => "You can only edit your own profile"
    end
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if current_user.priv_lvl < 2 && current_user != @user
      redirect_to :root , :alert => "You can only edit your own profile"
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.active = false
    @user.priv_lvl = 0
    respond_to do |format|
      if @user.save
        
        # Sends email to user when user is created.
        AutoMailer.sample_email(User.find(2), @user).deliver_now
        if current_user 
          format.html { redirect_to users_url, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { redirect_to "/welcome" }
        end
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def approve
    @user.active = true
    @user.priv_lvl = 1
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User was successfully Approved.' }
        format.json { head :no_content }
       else
        flash[:alert]= 'Error Approving'
        redirect_to users_path
      end
    end
    
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    
    def authorize
      if !current_user
         redirect_to :login , :alert => "You must be logged in to access this page"
      end
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :password, :password_confirmation, :avatar, :school, :city, :counrty, :occupation, :debate_experience, :familiar, :priv_lvl, :active, :rcv_emails)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-lg-6" style="padding-left:30px;">
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>


  <div class="form-inputs">
    
    
    <div class="panel panel-default" >
    <div class="panel-heading" ><h4 >General Information</h4></div>
    <div class="panel-body">
      

    <%= f.input :fname, label: 'First Name' %>
    <%= f.input :lname, label: 'Last Name' %>
    <%= f.input :password, label: 'Password', placeholder: 'Don\'t share your password with anyone!' %>
    <%= f.input :password_confirmation, label: 'Password Confirmation' %> 
    <%= f.input :email %> 
    <%= f.input :school %>
    <%= f.input :counrty, label: 'Country' %>
    <%= f.input :city %>
    <%= f.input :occupation %>
    <% if params[:action] == "edit" %>
    <h3> Current Image </h3>
      <img src="<%= @user.avatar %>" style ="width:200px;height:200px;" />
    <% end %>
    <%= f.input :avatar, as: :file, wrapper_html: { id: 'pictureInput' } %>
    <div id="target" style="width:200px;height:200px;"></div>
    <div class="row">
      <div class="col-lg-5">
        <%= f.input :debate_experience, label: 'Has previous debate experience' %>
      </div>
      <div class="col-lg-4">
        <%= f.input :familiar, label: 'Familiar with THIMUN' %>
      </div>
    </div>
    
    </div>
    </div>
    
    <% if current_user && current_user.priv_lvl >1  %>
    <div class="panel panel-default" >
    <div class="panel-heading" ><h4 >Administrative Options</h4></div>
    <div class="panel-body">
      
    
    <% if current_user.priv_lvl == 3  %>
     <%= f.input :priv_lvl, label: 'Privilage Level', collection: [["Basic Member",1],["Content Adminstrator",2],["Full Adminstrator",3]] %>
    <% end%>
     <%= f.input :active, label: 'Status',collection: [["Active",true],["Blocked",false]] %>
     <%= f.input :rcv_emails, label: 'Include in the mailing list' %>

    </div>
    
  </div>
      <% end %>
  </div>
  <div class ="row">
    <div class = "col-lg-2">
  <div class="form-actions">
    <%= f.button :submit , "Sign Up" %>
  </div>
  </div>
      <div class = "col-lg-1">
    <%= link_to 'Cancel', :root, class: "btn btn-danger", :style => "color:white;" %>
    </div>
  </div>
<% end %>
</div>
</div>

<script>
  $(function() {
  $('#pictureInput').on('change', function(event) {
    var files = event.target.files;
    var image = files[0]
    // here's the file size
    console.log(image.size);
    var reader = new FileReader();
    reader.onload = function(file) {
      var img = new Image();
      console.log(file);
      img.src = file.target.result;
      img.height = 200;
      $('#target').html(img);
    }
    reader.readAsDataURL(image);
    console.log(files);
  });
});
</script>

app/views/users/_tablecurrent.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>School</th>
      <th>Counrty</th>
      <th>Occupation</th>
      <th>Privilage Level</th>
      <th>Status</th>
      <th colspan="3"> Management Options</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each  do |user| %>
      <tr>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= user.school %></td>
        <td><%= user.counrty %></td>
        <td><%= user.occupation %></td>
        <td>
          <% if user.priv_lvl ==1 %>
            Basic Member
          <% elsif user.priv_lvl ==2 %>
            Content Administrator
          <% else %>
            Full Administrator
          <%end%>
          </td>
        <td><% if user.active %>
        <strong style="color:green;"> Active </strong>
        <% else %>
        <strong style="color:red;"> Blocked </strong>
        <% end%>
        </td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_tablepending.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>School</th>
      <th>Counrty</th>
      <th>Occupation</th>
      <th>Privilage Level</th>
      <th colspan="2"> Management Options</th>
    </tr>
  </thead>

  <tbody>
    <% @users.where(:priv_lvl => 0).each  do |user| %>
      <tr>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= user.school %></td>
        <td><%= user.counrty %></td>
        <td><%= user.occupation %></td>
        <td>
            Pending Approval
        </td>

        <td><%= link_to 'Approve', approve_user_path(user), class: "btn btn-success", :style => "color:white;" %> <%= link_to 'Reject', user, class: "btn btn-danger", :style => "margin-left:20px;color:white;", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
  <%= render "layouts/navigation"%>
<section class="black" style="margin-bottom:20px;margin-top:50px;">
<h1 style="padding-left:15px;">Editing User Profile</h1>
</section>
<%= render 'form' %>
<div class="row">
    <div class="col-lg-4"></div>
        <div class="col-lg-6">
<%= link_to 'Back to Users', users_path,  class: "btn btn-default" %> 
<%= link_to 'Cancel', @user, class: "btn btn-danger", :style => "color:white;" %>
</div>

</div>

app/views/users/index.html.erb
  <%= render "layouts/navigation"%>
     <section class="black" style="margin-top:50px;">
       
<h2 style="padding-left:20px;">Manage Users</h2>
     </section>
     

    <div class="bs-example">
        <ul class="nav nav-tabs" >
            <li class="active"><a data-toggle="tab" href="#Current"> Current</a></li>
            <li><a data-toggle="tab" href="#Pending">Pending (<%=  @users.where(:priv_lvl => 0).count %>)</a></li>
        </ul>
        <div class="tab-content">
            
            <div id="Current" class="tab-pane fade in active" >
                
                <%= render "tablecurrent"%>
                
            </div>
          
            <div id="Pending" class="tab-pane fade">
                <%= render "tablepending"%>
            </div>
            
        </div>
    </div>
    
<p id="notice"><%= notice %></p>

<br>


     <div class="col-md-6"><%= link_to new_user_path, class: 'btn btn-success', :style => "color:white;" do %>
                            <i class="glyphicon glyphicon-plus"></i> Add
                          <%end%></div>

app/views/users/new.html.erb
<section style="margin-bottom:20px;" class="black">
       
<h2 style="padding-left:20px;">Sign Up</h2>
     </section>
<%= render 'form' %>

app/views/users/show.html.erb
  <%= render "layouts/navigation"%>
 <!-- style="background:url(<%= @user.avatar%>);background-size:cover;" -->
 <section class="green" >
   <div class="row">
      <div class = "col-lg-2">
       <img src=<%= @user.avatar %>   data-toggle="tooltip" title="Edit Profile Picture" class="img-circle"  width="220" height="220" style="margin-left:20px;" > </a>
     </div>
     <div class = "col-lg-10">
       <h2 style ="padding-left:15px;margin-top:85px;font-size:55px;font-weight:bold;"><%= @user.fname %> <%= @user.lname %><span style="font-weight:400;">'s Profile </span> </h2>
     </div>
 </div>
 </section>
 
<p id="notice"><%= notice %></p>

<div style="padding-left:15px;">
<p>
  <strong>Email</strong>
  <%= @user.email %>
</p>

<p>
  <strong>School</strong>
  <%= @user.school %>
</p>

<p>
  <strong>City</strong>
  <%= @user.city %>
</p>

<p>
  <strong>Country</strong>
  <%= @user.counrty %>
</p>

<p>
  <strong>Occupation</strong>
  <%= @user.occupation %>
</p>

<p>
  <strong>Previous Debate Experience?</strong>
    <% if @user.debate_experience %>
    Yes
    <% else%>
    No
  <% end %>
</p>

<p>
  <strong>Familiar With THIMUN?</strong>
  <% if @user.familiar %>
    Yes
    <% else%>
    No
  <% end %>
</p>

<p>
  <strong>Privilage Level</strong>
  <% if @user.priv_lvl == 0 %>
    Pending
  <% elsif @user.priv_lvl ==1 %>
    Basic Member
  <% elsif @user.priv_lvl ==2 %>
    Content Administrator
  <% else %>
    Full Administrator
  <%end%>
</p>

<p>
  <strong>Active?</strong>
    <% if @user.familiar %>
    Yes
    <% else%>
    No
  <% end %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
</div>