config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :attendees
  resources :events do
    post :attend, on: :member
    post :leave, on: :member
  end
  resources :blogs
  resources :users do
    get :approve, on: :member
  end
  root to: 'visitors#index'
  get '/welcome' => "pages#welcome"
  get '/community' => "pages#community"
    get '/videos' => "pages#videos"
  get '/contact' => "pages#contact"
    get '/fun' => "pages#fun"
  get '/general-education' => "pages#general-education"
    get '/troubleshooting' => "pages#troubleshooting"
  get '/Security' => "pages#Security"
  get '/debate-info' => "pages#debate-info"
  get '/Assembly' => "pages#Assembly"
  get '/court' => "pages#court"
  get '/special' => "pages#special"
  get '/jro-mun' => "pages#jro-mun"
  get '/advise' => "pages#advise"
    get '/internationalAffairs' => "pages#internationalAffairs"

 get '/community' => "pages#community"

  get '/omunresources' => "pages#omunresources"
  get '/contact' => "pages#contact"
    get '/hela' => "pages#hela"
  get '/thimun_qatar' => "pages#thimun_qatar"
  
  get '/thimun-o-mun-rules-and-procedures' => "pages#thimun-o-mun-rules-and-procedures"
  
  get '/speech-making-and-forms-address' => "pages#speech-making-and-forms-address"
  get '/opening-speeches-policy-statements-and-draft-resolutions' => "pages#opening-speeches-policy-statements-and-draft-resolutions"
  get '/commonly-used-terms' => "pages#commonly-used-terms"
  get '/debate-procedure' => "pages#debate-procedure"
  get '/specific-rules-and-procedures-online-debates' => "pages#specific-rules-and-procedures-online-debates"
  get '/draft-resolution' => "pages#draft-resolution"
  get '/words-and-phrases-drafting-resolutions' => "pages#words-and-phrases-drafting-resolutions"
  get '/stock-chairing-phrases' => "pages#stock-chairing-phrases"

  
  get '/writing-thimun-resolution' => "pages#writing-thimun-resolution"
  
  get '/purpose-resolution' => "pages#purpose-resolution"
  get '/heading' => "pages#heading"
  get '/first-line' => "pages#first-line"
  get '/preambulatory-clauses' => "pages#preambulatory-clauses"
  get '/operative-clauses' => "pages#operative-clauses"
  get '/sample-resolution' => "pages#sample-resolution"
  

  
  get '/thimun-o-mun-delegate-guide' => "pages#thimun-o-mun-delegate-guide"
  
    
  get '/thimun-o-mun-vision' => "pages#thimun-o-mun-vision"
  get '/introduction' => "pages#introduction"
  get '/technology' => "pages#technology"
  get '/debating-blackboard-collaborate' => "pages#debating-blackboard-collaborate"
  get '/debate-procedure-step-step' => "pages#debate-procedure-step-step"
  get '/rules-procedures-online-equivalents' => "pages#rules-procedures-online-equivalents"
  get '/debate-cycles-country-assignments' => "pages#debate-cycles-country-assignments"
  get '/moderating-chairing' => "pages#moderating-chairing"

  
  get '/power-search' => "pages#power-search" 
  get '/un-guide-model-united-nations' => "pages#un-guide-model-united-nations" 

  
  
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  
  

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  
  # GET /attendees
  # GET /attendees.json
  def index
    @attendees = Attendee.all
  end

  # GET /attendees/1
  # GET /attendees/1.json
  def show
  end

  # GET /attendees/new
  def new
    @attendee = Attendee.new
  end

  # GET /attendees/1/edit
  def edit
  end

  # POST /attendees
  # POST /attendees.json
  def create
    @attendee = Attendee.new(attendee_params)

    respond_to do |format|
      if @attendee.save
        format.html { redirect_to @attendee, notice: 'Attendee was successfully created.' }
        format.json { render :show, status: :created, location: @attendee }
      else
        format.html { render :new }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendees/1
  # PATCH/PUT /attendees/1.json
  def update
    respond_to do |format|
      if @attendee.update(attendee_params)
        format.html { redirect_to @attendee, notice: 'Attendee was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendee }
      else
        format.html { render :edit }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1
  # DELETE /attendees/1.json
  def destroy
    @attendee.destroy
    respond_to do |format|
      format.html { redirect_to attendees_url, notice: 'Attendee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendee
      @attendee = Attendee.find(params[:id])
    end
    
    def authorize
      unless current_user && current_user.priv_lvl > 2
         redirect_to :root , :alert => "You must be logged in to access this page"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendee_params
      params.require(:attendee).permit(:user_id, :event_id)
    end
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/views/attendees/_form.html.erb
<%= simple_form_for(@attendee) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :event_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/attendees/edit.html.erb
<h1>Editing Attendee</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendee %> |
<%= link_to 'Back', attendees_path %>

app/views/attendees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Attendees</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendees.each do |attendee| %>
      <tr>
        <td><%= attendee.user_id %></td>
        <td><%= attendee.event_id %></td>
        <td><%= link_to 'Show', attendee %></td>
        <td><%= link_to 'Edit', edit_attendee_path(attendee) %></td>
        <td><%= link_to 'Destroy', attendee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendee', new_attendee_path %>

app/views/attendees/new.html.erb
<h1>New Attendee</h1>

<%= render 'form' %>

<%= link_to 'Back', attendees_path %>

app/views/attendees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @attendee.user_id %>
</p>

<p>
  <strong>Event:</strong>
  <%= @attendee.event_id %>
</p>

<%= link_to 'Edit', edit_attendee_path(@attendee) %> |
<%= link_to 'Back', attendees_path %>