config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :attendees
  resources :events do
    post :attend, on: :member
    post :leave, on: :member
  end
  resources :blogs
  resources :users do
    get :approve, on: :member
  end
  root to: 'visitors#index'
  get '/welcome' => "pages#welcome"
  get '/community' => "pages#community"
    get '/videos' => "pages#videos"
  get '/contact' => "pages#contact"
    get '/fun' => "pages#fun"
  get '/general-education' => "pages#general-education"
    get '/troubleshooting' => "pages#troubleshooting"
  get '/Security' => "pages#Security"
  get '/debate-info' => "pages#debate-info"
  get '/Assembly' => "pages#Assembly"
  get '/court' => "pages#court"
  get '/special' => "pages#special"
  get '/jro-mun' => "pages#jro-mun"
  get '/advise' => "pages#advise"
    get '/internationalAffairs' => "pages#internationalAffairs"

 get '/community' => "pages#community"

  get '/omunresources' => "pages#omunresources"
  get '/contact' => "pages#contact"
    get '/hela' => "pages#hela"
  get '/thimun_qatar' => "pages#thimun_qatar"
  
  get '/thimun-o-mun-rules-and-procedures' => "pages#thimun-o-mun-rules-and-procedures"
  
  get '/speech-making-and-forms-address' => "pages#speech-making-and-forms-address"
  get '/opening-speeches-policy-statements-and-draft-resolutions' => "pages#opening-speeches-policy-statements-and-draft-resolutions"
  get '/commonly-used-terms' => "pages#commonly-used-terms"
  get '/debate-procedure' => "pages#debate-procedure"
  get '/specific-rules-and-procedures-online-debates' => "pages#specific-rules-and-procedures-online-debates"
  get '/draft-resolution' => "pages#draft-resolution"
  get '/words-and-phrases-drafting-resolutions' => "pages#words-and-phrases-drafting-resolutions"
  get '/stock-chairing-phrases' => "pages#stock-chairing-phrases"

  
  get '/writing-thimun-resolution' => "pages#writing-thimun-resolution"
  
  get '/purpose-resolution' => "pages#purpose-resolution"
  get '/heading' => "pages#heading"
  get '/first-line' => "pages#first-line"
  get '/preambulatory-clauses' => "pages#preambulatory-clauses"
  get '/operative-clauses' => "pages#operative-clauses"
  get '/sample-resolution' => "pages#sample-resolution"
  

  
  get '/thimun-o-mun-delegate-guide' => "pages#thimun-o-mun-delegate-guide"
  
    
  get '/thimun-o-mun-vision' => "pages#thimun-o-mun-vision"
  get '/introduction' => "pages#introduction"
  get '/technology' => "pages#technology"
  get '/debating-blackboard-collaborate' => "pages#debating-blackboard-collaborate"
  get '/debate-procedure-step-step' => "pages#debate-procedure-step-step"
  get '/rules-procedures-online-equivalents' => "pages#rules-procedures-online-equivalents"
  get '/debate-cycles-country-assignments' => "pages#debate-cycles-country-assignments"
  get '/moderating-chairing' => "pages#moderating-chairing"

  
  get '/power-search' => "pages#power-search" 
  get '/un-guide-model-united-nations' => "pages#un-guide-model-united-nations" 

  
  
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  
  

end

app/models/event.rb
class Event < ActiveRecord::Base
    belongs_to :user, foreign_key: :user_id
     
    validates :name, :topic, :start_time, :end_time, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :leave]
  before_action :authorize, only: [ :edit, :update, :create, :new, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    
    respond_to do |format|
        begin
          format.html
          format.xlsx {
          render xlsx: 'events', template: 'events/show', filename: "#{@event.name} Event Attendees List.xlsx"
          }
          
          rescue TypeError
            redirect_to customer_request_path, notice: 'Couldn\'t Generate Attendees List'
          end
      end
      
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def attend
  
    @attendee = Attendee.new do |c|
      c.user_id = current_user.id
      c.event_id = params[:id]
    end
    
    if @attendee.save
      flash[:alert]= 'You will be attending this event'
      redirect_to event_path
    else
      flash[:alert]= 'Error Attending Event'
      redirect_to event_path
    end
    
  end
  
  def leave
    
    @attendee = Attendee.find_by(user_id: current_user.id, event_id: @event.id)
    @attendee.destroy
    respond_to do |format|
      format.html { redirect_to event_path, notice: 'You won\'t be attending this event' }
      format.json { head :no_content }
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end
    
    def authorize
      if !current_user
         redirect_to :login , :alert => "You must be logged in to access this page"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :user_id, :topic, :commitee, :addtnl_info, :rgstr_end, :start_time, :end_time)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>
 
  <div style="padding-top:10px;"></div>
  <div class="form-inputs">
        <div class="row">
    <div class="col-lg-6">
    <h3> Starts..</h3>
    <%= f.input :start_time, label: false %>
    
    </div>
    <div class="col-lg-6">
    <h3> Ends..</h3>
    <%= f.input :end_time, label: false %>
    <strong style="color:grey;"> <i class="glyphicon glyphicon-time"></i>  All event times are in <a href="http://www.thetimezoneconverter.com/" target="_blank"> UTC </a> </strong>
    </div>
    
    </div>
    
    <div style="margin-bottom:30px;"></div>
    <%= f.input :name, label: "Event Name" %>
    <%= f.input :topic, label: "Event Topic" %>
    <%= f.input :commitee, label: "Commitee" %>
    <%= f.input :rgstr_end, label: " Registration Ends at.." %>
    <div style="margin-bottom:50px"></div>
    <%= f.input :addtnl_info,  label: false, placeholder: "Additional Info" %>
    



  </div>
  
  <div class="row" style="padding-bottom:50px;padding-top:40px;">
    <div class="col-lg-2">
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
  </div>
  <%= link_to 'Cancel', events_path, class: "btn btn-danger", style: "color:white" %>
  </div>
<% end %>
 

app/views/events/edit.html.erb
<section class="black" style="padding-bottom:30px;">
<h1 style="padding-top:50px;padding-bottom:20px;color:white;padding-left:10px;font-size:50px;">Editing Event</h1>
</section>
<div class="col-lg-9">
<%= render 'form' %>
</div>

app/views/events/index.html.erb
<script type="text/javascript" src="date_time.js"></script>
<%= render "layouts/navigation" %>
<p id="notice"><%= notice %></p>
<br>

<!-- <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Topic</th>
      <th>Commitee</th>
      <th>Rgstr end</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.user_id %></td>
        <td><%= event.topic %></td>
        <td><%= event.commitee %></td>
        <td><%= event.rgstr_end %></td>
        <td><%= event.start_time %></td>
        <td><%= event.end_time %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

<br>



<br>
<!-- ########################## Calendar ############################# -->

<div class="row">
<div class="col-lg-9">
<%= month_calendar events: @events do |date, events| %>
  <%= date.day %>
  <% events.each do |event| %>
    <div>
      <%= link_to event.name, event %>
    </div>
  <% end %>
<% end %>
</div>

<!-- ########################## Side Event List ############################# -->

<div class="col-lg-3">
  <h2 >Current Events</h2>
<table class="table ">
  <thead>
    <tr>
      <th>Name</th>
      <th>Starts</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td> <%= link_to  event.name, event %></td>
        <% if current_user %>
          <% if Attendee.find_by(user_id: current_user.id, event_id: event.id)%>
          <td><strong style="color:green;"><%= event.start_time %></strong></td>
          <% else %>
          <td><strong><%= event.start_time %></strong></td> 
          <% end %>
        <%else %>
          <td><strong><%= event.start_time %></strong></td>          
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Add Event", new_event_path, class: "btn btn-success", style: "color:white;"%>

</div>

</div>

<!--footer start from here-->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-6 footerleft ">
        <div class="logofooter"> About US</div>
        <p>O-MUN is open to  high school students with the goal of bringing a quality Model United Nation's experience to youth around the world, and at no cost. 
        <br>
        </br>O-MUN is a proud THIMUN Partner.</p>
        <p><i class="fa fa-map-pin"></i> 210, Aggarwal Tower, Rohini sec 9, New Delhi -        110085, INDIA</p>
        <p><i class="fa fa-phone"></i> Phone (India) : +91 9999 878 398</p>
        <p><i class="fa fa-envelope"></i> E-mail : info@webenlance.com</p>
        
      </div>
      <div class="col-md-4 col-sm-6 footerleft ">
        <h6 class="heading7">Travel Teams</h6>
        <p>THIMUN OMUN will be hosting one travel team this year, to THIMUN Qatar 2016.<br></br>
        An expression of interest form is now available.  Please complete the form, which can be found here.<br></br>
        Note that THIMUN OMUN does not fund student MUN trips. Eligible candidates will be emailed further information by June 30th.</p>
      </div>
      <div class="col-md-3 col-sm-6 paddingtop-bottom">
        <h6 class="heading7">LATEST POST</h6>
        <div class="post">          
            <blockquote cite="https://twitter.com/onlinemun"><a href="https://twitter.com/onlinemun"><div class="color"> Twitter </div></a></blockquote>
         
          <p>Hello delegates! The first International Affairs Dialogue of 2017 on "The Question of Sri Lanka: Promoting Ethnic... https://t.co/JMaZ1DHCl <span>August 3,2015</span></p>
          <p>Anmol shares his thoughts on his passion for MUN, something many O-MUN delegates relate to! https://t.co/SoHzYoYFBn  <span>August 3,2015</span></p>
          <p>Happening now: our MUN workshop is starting in the General Assembly room! #MUN101 https://t.co/wEWgW5fDq7 <span>August 3,2015</span></p>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 paddingtop-bottom">
        <div class="fb-page" data-href="https://www.facebook.com/facebook" data-tabs="timeline" data-height="300" data-small-header="false" style="margin-bottom:15px;" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
        </div>
      </div>
    </div>
  </div>
</footer>
<!--footer start from here-->

<div class="copyright">
  <div class="container">
    <div class="col-md-6">
      <p>© 2016 - All Rights with Webenlance</p>
    </div>
    <div class="col-md-6">
      <ul class="bottom_ul">
        <li><a href="#">webenlance.com</a></li>
        <li><a href="#">About us</a></li>
        <li><a href="#">Blog</a></li>
        <li><a href="#">Faq's</a></li>
        <li><a href="#">Contact us</a></li>

      </ul>
    </div>
  </div>
</div>

<script>
  function date_time(id)
{
        date = new Date;
        year = date.getFullYear();
        month = date.getMonth();
        months = new Array('January', 'February', 'March', 'April', 'May', 'June', 'Jully', 'August', 'September', 'October', 'November', 'December');
        d = date.getDate();
        day = date.getDay();
        days = new Array('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday');
        h = date.getHours();
        if(h<10)
        {
                h = "0"+h;
        }
        m = date.getMinutes();
        if(m<10)
        {
                m = "0"+m;
        }
        s = date.getSeconds();
        if(s<10)
        {
                s = "0"+s;
        }
        result = ''+days[day]+' '+months[month]+' '+d+' '+year+' '+h+':'+m+':'+s;
        document.getElementById(id).innerHTML = result;
        setTimeout('date_time("'+id+'");','1000');
        return true;
}
</script>

app/views/events/new.html.erb
<%= render "layouts/navigation" %>
<section class="green" style="padding-bottom:30px;">
<h1 style="padding-top:50px;padding-bottom:20px;color:white;padding-left:10px;font-size:50px;">New Event</h1>
</section>

<div class="col-lg-9">
<%= render 'form' %>
</div>

app/views/events/show.html.erb
<%= render "layouts/navigation" %>
<p id="notice"><%= notice %></p>
<body style="padding-left:20px;">
  
<div class="row" style="margin-bottom:40px;margin-top:40px;">
  <div class="col-lg-9">
    <!-- Edit Event Option For Admins -->
  
    <% if current_user && current_user.priv_lvl > 1 %>
    <div class="col-lg-10">
    <%= link_to  edit_event_path(@event), class: "btn btn-block btn-default", style: "padding:8px;margin-top:20px;"  do %> <i class="glyphicon glyphicon-edit" ></i> Edit<%end%>
    </div>
    <div class="col-lg-1">
    <%= link_to  @event, method: :delete, class: "btn btn-block btn-danger",  data: { confirm: 'Are you sure you want to delete this event ? This action can\'t be reversed. ' }, style: "padding:8px;margin-top:20px;color:white;"  do %> <i class="glyphicon glyphicon-trash" ></i><%end%>
    </div>
    <% end %>
    
    <% if current_user && Attendee.find_by(user_id: current_user.id, event_id: @event.id) %>
    <h1 style="font-size:100px; color:#4dd15c;" ><strong data-toggle="tooltip" title="You're Attending this Event!" data-placement="right"><%= @event.name %></strong></h1> 
    <% else %>
    <h1 style="font-size:100px;"><strong><%= @event.name %></strong></h1> 
    <% end %>
    <p style="color:#dddddd;font-size:20px;">
      <strong>by </strong>
      <%= User.find(@event.user_id).fname %>   <%= User.find(@event.user_id).lname %>
    </p>
    
  </div>

</div>

<div class="row">
    <div class="col-lg-6">
      <h2>
        <%= @event.topic %>
      </h2>
    
      <h3>
        <%= @event.commitee %>
      </h3>
    
      <p> <%= @event.addtnl_info %> </p>
      <p>
      <strong>Registration Ends:</strong>
      <%= @event.rgstr_end %>
      </p>
      <hr>
      <div class="col-lg-6">
      <!-- ######### Attendees #######-->
       <% attendee_count = 0%>
       <% @attendees = Attendee.where(:event_id => @event.id)%>
                    <% @attendees.each do |attendee| %>
                      <% attendee_count += 1 %>
                    <%end%>
                
  
      <h3>   <% if attendee_count == 1%>
    <h3 style="margin-left:-17px;"> 1 Attendee </h3>
  <%else%>
  <h3 style="margin-left:-17px;"> <%= attendee_count %> Attendees</h3>
  <%end%> 
  <div id="attends" class="collapse">
              <table class="table table-hover">
  
                  <% @attendees.each do |attendee| %>
                    <tr>
                      <td> <%= User.find(attendee.user_id).fname %>  <%=User.find(attendee.user_id).lname %> </td>
                      <!-- Country -->
                    </tr>
                  <% end %>
  
              </table>
        
        
      </div>
      
  </div>
  <div class ="col-lg-5">
    <div style="float:right;">
    <% if attendee_count != 0%>
    <%= link_to  event_path(format: :xlsx), class: "btn btn-success", :style => "color:white;margin-top:15px;" do %> <i class="glyphicon glyphicon-download-alt" data-toggle="tooltip" title="Download Attendees List" ></i> <%end%>
    <a class ="btn btn-primary" style="color:white;margin-top:15px;" data-toggle="collapse" data-target="#attends"> Show/Hide </a>
    <% end %>
    </div>
    </div>
    </div>
    
    
    <div class="col-lg-5"> 
        <p>
        <h3><strong>Starts</strong></h3>
        <%= @event.start_time %>
      </p>
      
      <p>
        <h3><strong>Ends</strong></h3>
        <%= @event.end_time %>
      </p>
      <p>
        <% if current_user %>
      <% if !Attendee.find_by(user_id: current_user.id, event_id: @event.id)%>
        <p style="color:#d3d3d3;"> You're not attending this event</p>
        <%= bootstrap_form_tag url: attend_event_path do |f| %>
            <%= f.submit "Attend", class: "btn btn-success", style: "padding:8px;color:white;" %>      
        <% end %>
      <% else%>
        <%= bootstrap_form_tag url: leave_event_path do |f| %>
            <p style="color:#adfc7b;"> You are attending this event</p>
            <%= f.submit "Leave", class: "btn btn-danger", style: "padding:8px;color:white;" %>      
        <% end %>
      <% end %>
    <% else %>
      <p> Sign in to attend this event ! </p>
    <% end %>
      </p>
      
    </div>

</div>

<div class="row" style="margin-top:15px;">
  <div class="col-lg-2" style=";"> </div>
  <div class="col-lg-2">  </div>
  <div class="col-lg-2">
   
  </div>

</div>

<div class="row" style="margin-top:70px;">
  <div class="col-lg-2" style=";"> <%= link_to 'Back', events_path, class: "btn btn-block btn-default", style: "padding:8px;"  %> </div>
 


</div>
</body>

<!-- Tool Tip -->
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>